# Weather Station Services Configuration Template  
# Replace placeholder values with your actual credentials  

# Database configuration  
database:  
  host: localhost  
  user: weather_user  
  password: your_secure_password  
  database: weather  
  port: 3306  # Default MySQL port  

# Weather services configuration  
services:  
  # Weather Underground  
  wunderground:  
    enabled: true  
    interval: 300  # Update interval in seconds (5 minutes)  
    credentials:  
      id: YOUR_STATION_ID  
      password: YOUR_PASSWORD  
      url: https://weatherstation.wunderground.com/weatherstation/updateweatherstation.php  
  
  # Weathercloud  
  weathercloud:  
    enabled: true  
    interval: 300  # Update interval in seconds (5 minutes)  
    credentials:  
      id: YOUR_WEATHERCLOUD_ID  
      key: YOUR_WEATHERCLOUD_KEY  
      url: https://api.weathercloud.net/v01/set  
  
  # Windy  
  windy:  
    enabled: true  
    interval: 300  # Update interval in seconds (5 minutes)  
    credentials:  
      # Full URL with embedded JWT token  
      url: "https://stations.windy.com/pws/update/YOUR_JWT_TOKEN?"  
  
  # PWS Weather  
  pwsweather:  
    enabled: true  
    interval: 300  # Update interval in seconds (5 minutes)  
    credentials:  
      id: YOUR_PWS_ID  
      password: YOUR_PWS_PASSWORD  
      url: https://www.pwsweather.com/pwsupdate/pwsupdate.php  
      software: WeatherStation 
  
  # Met Office (UK Weather Observations Website)  
  metoffice:  
    enabled: true  
    interval: 300  # Update interval in seconds (5 minutes)  
    credentials:  
      siteid: YOUR_SITE_ID  
      auth_key: YOUR_AUTH_KEY  
      url: https://wow.metoffice.gov.uk/automaticreading  
      software: WeatherStation 

# Logging configuration  
logging:  
  level: INFO  # Options: DEBUG, INFO, WARNING, ERROR, CRITICAL  
  file: /var/log/weather_station.log  
  max_size: 10485760  # 10MB  
  backup_count: 5
